import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';
import tailwindcss from '@tailwindcss/vite';
import mdx from '@astrojs/mdx';

export default defineConfig({
  site: 'https://wastewize.co.uk',
  output: 'static',
  adapter: vercel(),
  redirects: {
    '/house-clearance':          '/services/house-clearance',
    '/office-clearance':         '/services/office-clearance',
    '/end-of-tenancy-clearance': '/services/end-of-tenancy-clearance',
    '/fly-tipping-removal':      '/services/fly-tipping-removal',
    '/skip-hire-alternative':    '/services/skip-hire-alternative',

    // ── Phase 1: Middlesex → West London (alperton) ──────────────────────
    '/areas/middlesex/alperton':                            '/areas/west-london/alperton',
    '/areas/middlesex/alperton/asbestos-removal':           '/areas/west-london/alperton/asbestos-removal',
    '/areas/middlesex/alperton/builders-waste-removal':     '/areas/west-london/alperton/builders-waste-removal',
    '/areas/middlesex/alperton/commercial-clearance':       '/areas/west-london/alperton/commercial-clearance',
    '/areas/middlesex/alperton/confidential-waste':         '/areas/west-london/alperton/confidential-waste',
    '/areas/middlesex/alperton/electrical-equipment':       '/areas/west-london/alperton/electrical-equipment',
    '/areas/middlesex/alperton/end-of-tenancy-clearance':   '/areas/west-london/alperton/end-of-tenancy-clearance',
    '/areas/middlesex/alperton/fly-tipping-removal':        '/areas/west-london/alperton/fly-tipping-removal',
    '/areas/middlesex/alperton/garden-refuse':              '/areas/west-london/alperton/garden-refuse',
    '/areas/middlesex/alperton/house-clearance':            '/areas/west-london/alperton/house-clearance',
    '/areas/middlesex/alperton/office-clearance':           '/areas/west-london/alperton/office-clearance',
    '/areas/middlesex/alperton/residential-waste':          '/areas/west-london/alperton/residential-waste',
    '/areas/middlesex/alperton/rubble-wood-removal':        '/areas/west-london/alperton/rubble-wood-removal',
    '/areas/middlesex/alperton/scrap-metal-collection':     '/areas/west-london/alperton/scrap-metal-collection',
    '/areas/middlesex/alperton/skip-hire-alternative':      '/areas/west-london/alperton/skip-hire-alternative',
    '/areas/middlesex/alperton/strip-out-demolition':       '/areas/west-london/alperton/strip-out-demolition',

    // ── Phase 1: Middlesex → West London (brentford) ─────────────────────
    '/areas/middlesex/brentford':                           '/areas/west-london/brentford',
    '/areas/middlesex/brentford/asbestos-removal':          '/areas/west-london/brentford/asbestos-removal',
    '/areas/middlesex/brentford/builders-waste-removal':    '/areas/west-london/brentford/builders-waste-removal',
    '/areas/middlesex/brentford/commercial-clearance':      '/areas/west-london/brentford/commercial-clearance',
    '/areas/middlesex/brentford/confidential-waste':        '/areas/west-london/brentford/confidential-waste',
    '/areas/middlesex/brentford/electrical-equipment':      '/areas/west-london/brentford/electrical-equipment',
    '/areas/middlesex/brentford/end-of-tenancy-clearance':  '/areas/west-london/brentford/end-of-tenancy-clearance',
    '/areas/middlesex/brentford/fly-tipping-removal':       '/areas/west-london/brentford/fly-tipping-removal',
    '/areas/middlesex/brentford/garden-refuse':             '/areas/west-london/brentford/garden-refuse',
    '/areas/middlesex/brentford/house-clearance':           '/areas/west-london/brentford/house-clearance',
    '/areas/middlesex/brentford/office-clearance':          '/areas/west-london/brentford/office-clearance',
    '/areas/middlesex/brentford/residential-waste':         '/areas/west-london/brentford/residential-waste',
    '/areas/middlesex/brentford/rubble-wood-removal':       '/areas/west-london/brentford/rubble-wood-removal',
    '/areas/middlesex/brentford/scrap-metal-collection':    '/areas/west-london/brentford/scrap-metal-collection',
    '/areas/middlesex/brentford/skip-hire-alternative':     '/areas/west-london/brentford/skip-hire-alternative',
    '/areas/middlesex/brentford/strip-out-demolition':      '/areas/west-london/brentford/strip-out-demolition',

    // ── Phase 1: Middlesex → West London (kingsbury) ─────────────────────
    '/areas/middlesex/kingsbury':                           '/areas/west-london/kingsbury',
    '/areas/middlesex/kingsbury/asbestos-removal':          '/areas/west-london/kingsbury/asbestos-removal',
    '/areas/middlesex/kingsbury/builders-waste-removal':    '/areas/west-london/kingsbury/builders-waste-removal',
    '/areas/middlesex/kingsbury/commercial-clearance':      '/areas/west-london/kingsbury/commercial-clearance',
    '/areas/middlesex/kingsbury/confidential-waste':        '/areas/west-london/kingsbury/confidential-waste',
    '/areas/middlesex/kingsbury/electrical-equipment':      '/areas/west-london/kingsbury/electrical-equipment',
    '/areas/middlesex/kingsbury/end-of-tenancy-clearance':  '/areas/west-london/kingsbury/end-of-tenancy-clearance',
    '/areas/middlesex/kingsbury/fly-tipping-removal':       '/areas/west-london/kingsbury/fly-tipping-removal',
    '/areas/middlesex/kingsbury/garden-refuse':             '/areas/west-london/kingsbury/garden-refuse',
    '/areas/middlesex/kingsbury/house-clearance':           '/areas/west-london/kingsbury/house-clearance',
    '/areas/middlesex/kingsbury/office-clearance':          '/areas/west-london/kingsbury/office-clearance',
    '/areas/middlesex/kingsbury/residential-waste':         '/areas/west-london/kingsbury/residential-waste',
    '/areas/middlesex/kingsbury/rubble-wood-removal':       '/areas/west-london/kingsbury/rubble-wood-removal',
    '/areas/middlesex/kingsbury/scrap-metal-collection':    '/areas/west-london/kingsbury/scrap-metal-collection',
    '/areas/middlesex/kingsbury/skip-hire-alternative':     '/areas/west-london/kingsbury/skip-hire-alternative',
    '/areas/middlesex/kingsbury/strip-out-demolition':      '/areas/west-london/kingsbury/strip-out-demolition',

    // ── Phase 1: Middlesex → West London (sudbury) ───────────────────────
    '/areas/middlesex/sudbury':                             '/areas/west-london/sudbury',
    '/areas/middlesex/sudbury/asbestos-removal':            '/areas/west-london/sudbury/asbestos-removal',
    '/areas/middlesex/sudbury/builders-waste-removal':      '/areas/west-london/sudbury/builders-waste-removal',
    '/areas/middlesex/sudbury/commercial-clearance':        '/areas/west-london/sudbury/commercial-clearance',
    '/areas/middlesex/sudbury/confidential-waste':          '/areas/west-london/sudbury/confidential-waste',
    '/areas/middlesex/sudbury/electrical-equipment':        '/areas/west-london/sudbury/electrical-equipment',
    '/areas/middlesex/sudbury/end-of-tenancy-clearance':    '/areas/west-london/sudbury/end-of-tenancy-clearance',
    '/areas/middlesex/sudbury/fly-tipping-removal':         '/areas/west-london/sudbury/fly-tipping-removal',
    '/areas/middlesex/sudbury/garden-refuse':               '/areas/west-london/sudbury/garden-refuse',
    '/areas/middlesex/sudbury/house-clearance':             '/areas/west-london/sudbury/house-clearance',
    '/areas/middlesex/sudbury/office-clearance':            '/areas/west-london/sudbury/office-clearance',
    '/areas/middlesex/sudbury/residential-waste':           '/areas/west-london/sudbury/residential-waste',
    '/areas/middlesex/sudbury/rubble-wood-removal':         '/areas/west-london/sudbury/rubble-wood-removal',
    '/areas/middlesex/sudbury/scrap-metal-collection':      '/areas/west-london/sudbury/scrap-metal-collection',
    '/areas/middlesex/sudbury/skip-hire-alternative':       '/areas/west-london/sudbury/skip-hire-alternative',
    '/areas/middlesex/sudbury/strip-out-demolition':        '/areas/west-london/sudbury/strip-out-demolition',

    // ── Phase 1: Middlesex → West London (wembley) ───────────────────────
    '/areas/middlesex/wembley':                             '/areas/west-london/wembley',
    '/areas/middlesex/wembley/asbestos-removal':            '/areas/west-london/wembley/asbestos-removal',
    '/areas/middlesex/wembley/builders-waste-removal':      '/areas/west-london/wembley/builders-waste-removal',
    '/areas/middlesex/wembley/commercial-clearance':        '/areas/west-london/wembley/commercial-clearance',
    '/areas/middlesex/wembley/confidential-waste':          '/areas/west-london/wembley/confidential-waste',
    '/areas/middlesex/wembley/electrical-equipment':        '/areas/west-london/wembley/electrical-equipment',
    '/areas/middlesex/wembley/end-of-tenancy-clearance':    '/areas/west-london/wembley/end-of-tenancy-clearance',
    '/areas/middlesex/wembley/fly-tipping-removal':         '/areas/west-london/wembley/fly-tipping-removal',
    '/areas/middlesex/wembley/garden-refuse':               '/areas/west-london/wembley/garden-refuse',
    '/areas/middlesex/wembley/house-clearance':             '/areas/west-london/wembley/house-clearance',
    '/areas/middlesex/wembley/office-clearance':            '/areas/west-london/wembley/office-clearance',
    '/areas/middlesex/wembley/residential-waste':           '/areas/west-london/wembley/residential-waste',
    '/areas/middlesex/wembley/rubble-wood-removal':         '/areas/west-london/wembley/rubble-wood-removal',
    '/areas/middlesex/wembley/scrap-metal-collection':      '/areas/west-london/wembley/scrap-metal-collection',
    '/areas/middlesex/wembley/skip-hire-alternative':       '/areas/west-london/wembley/skip-hire-alternative',
    '/areas/middlesex/wembley/strip-out-demolition':        '/areas/west-london/wembley/strip-out-demolition',

    // ── Phase 1: Middlesex → North London (edgware) ──────────────────────
    '/areas/middlesex/edgware':                             '/areas/north-london/edgware',
    '/areas/middlesex/edgware/asbestos-removal':            '/areas/north-london/edgware/asbestos-removal',
    '/areas/middlesex/edgware/builders-waste-removal':      '/areas/north-london/edgware/builders-waste-removal',
    '/areas/middlesex/edgware/commercial-clearance':        '/areas/north-london/edgware/commercial-clearance',
    '/areas/middlesex/edgware/confidential-waste':          '/areas/north-london/edgware/confidential-waste',
    '/areas/middlesex/edgware/electrical-equipment':        '/areas/north-london/edgware/electrical-equipment',
    '/areas/middlesex/edgware/end-of-tenancy-clearance':    '/areas/north-london/edgware/end-of-tenancy-clearance',
    '/areas/middlesex/edgware/fly-tipping-removal':         '/areas/north-london/edgware/fly-tipping-removal',
    '/areas/middlesex/edgware/garden-refuse':               '/areas/north-london/edgware/garden-refuse',
    '/areas/middlesex/edgware/house-clearance':             '/areas/north-london/edgware/house-clearance',
    '/areas/middlesex/edgware/office-clearance':            '/areas/north-london/edgware/office-clearance',
    '/areas/middlesex/edgware/residential-waste':           '/areas/north-london/edgware/residential-waste',
    '/areas/middlesex/edgware/rubble-wood-removal':         '/areas/north-london/edgware/rubble-wood-removal',
    '/areas/middlesex/edgware/scrap-metal-collection':      '/areas/north-london/edgware/scrap-metal-collection',
    '/areas/middlesex/edgware/skip-hire-alternative':       '/areas/north-london/edgware/skip-hire-alternative',
    '/areas/middlesex/edgware/strip-out-demolition':        '/areas/north-london/edgware/strip-out-demolition',

    // ── Phase 1: Middlesex → North London (hendon) ───────────────────────
    '/areas/middlesex/hendon':                              '/areas/north-london/hendon',
    '/areas/middlesex/hendon/asbestos-removal':             '/areas/north-london/hendon/asbestos-removal',
    '/areas/middlesex/hendon/builders-waste-removal':       '/areas/north-london/hendon/builders-waste-removal',
    '/areas/middlesex/hendon/commercial-clearance':         '/areas/north-london/hendon/commercial-clearance',
    '/areas/middlesex/hendon/confidential-waste':           '/areas/north-london/hendon/confidential-waste',
    '/areas/middlesex/hendon/electrical-equipment':         '/areas/north-london/hendon/electrical-equipment',
    '/areas/middlesex/hendon/end-of-tenancy-clearance':     '/areas/north-london/hendon/end-of-tenancy-clearance',
    '/areas/middlesex/hendon/fly-tipping-removal':          '/areas/north-london/hendon/fly-tipping-removal',
    '/areas/middlesex/hendon/garden-refuse':                '/areas/north-london/hendon/garden-refuse',
    '/areas/middlesex/hendon/house-clearance':              '/areas/north-london/hendon/house-clearance',
    '/areas/middlesex/hendon/office-clearance':             '/areas/north-london/hendon/office-clearance',
    '/areas/middlesex/hendon/residential-waste':            '/areas/north-london/hendon/residential-waste',
    '/areas/middlesex/hendon/rubble-wood-removal':          '/areas/north-london/hendon/rubble-wood-removal',
    '/areas/middlesex/hendon/scrap-metal-collection':       '/areas/north-london/hendon/scrap-metal-collection',
    '/areas/middlesex/hendon/skip-hire-alternative':        '/areas/north-london/hendon/skip-hire-alternative',
    '/areas/middlesex/hendon/strip-out-demolition':         '/areas/north-london/hendon/strip-out-demolition',

    // ── Phase 1: Middlesex → North London (southgate) ────────────────────
    '/areas/middlesex/southgate':                           '/areas/north-london/southgate',
    '/areas/middlesex/southgate/asbestos-removal':          '/areas/north-london/southgate/asbestos-removal',
    '/areas/middlesex/southgate/builders-waste-removal':    '/areas/north-london/southgate/builders-waste-removal',
    '/areas/middlesex/southgate/commercial-clearance':      '/areas/north-london/southgate/commercial-clearance',
    '/areas/middlesex/southgate/confidential-waste':        '/areas/north-london/southgate/confidential-waste',
    '/areas/middlesex/southgate/electrical-equipment':      '/areas/north-london/southgate/electrical-equipment',
    '/areas/middlesex/southgate/end-of-tenancy-clearance':  '/areas/north-london/southgate/end-of-tenancy-clearance',
    '/areas/middlesex/southgate/fly-tipping-removal':       '/areas/north-london/southgate/fly-tipping-removal',
    '/areas/middlesex/southgate/garden-refuse':             '/areas/north-london/southgate/garden-refuse',
    '/areas/middlesex/southgate/house-clearance':           '/areas/north-london/southgate/house-clearance',
    '/areas/middlesex/southgate/office-clearance':          '/areas/north-london/southgate/office-clearance',
    '/areas/middlesex/southgate/residential-waste':         '/areas/north-london/southgate/residential-waste',
    '/areas/middlesex/southgate/rubble-wood-removal':       '/areas/north-london/southgate/rubble-wood-removal',
    '/areas/middlesex/southgate/scrap-metal-collection':    '/areas/north-london/southgate/scrap-metal-collection',
    '/areas/middlesex/southgate/skip-hire-alternative':     '/areas/north-london/southgate/skip-hire-alternative',
    '/areas/middlesex/southgate/strip-out-demolition':      '/areas/north-london/southgate/strip-out-demolition',

    // ── Phase 1: Middlesex → Surrey (shepperton) ─────────────────────────
    '/areas/middlesex/shepperton':                          '/areas/surrey/shepperton',
    '/areas/middlesex/shepperton/asbestos-removal':         '/areas/surrey/shepperton/asbestos-removal',
    '/areas/middlesex/shepperton/builders-waste-removal':   '/areas/surrey/shepperton/builders-waste-removal',
    '/areas/middlesex/shepperton/commercial-clearance':     '/areas/surrey/shepperton/commercial-clearance',
    '/areas/middlesex/shepperton/confidential-waste':       '/areas/surrey/shepperton/confidential-waste',
    '/areas/middlesex/shepperton/electrical-equipment':     '/areas/surrey/shepperton/electrical-equipment',
    '/areas/middlesex/shepperton/end-of-tenancy-clearance': '/areas/surrey/shepperton/end-of-tenancy-clearance',
    '/areas/middlesex/shepperton/fly-tipping-removal':      '/areas/surrey/shepperton/fly-tipping-removal',
    '/areas/middlesex/shepperton/garden-refuse':            '/areas/surrey/shepperton/garden-refuse',
    '/areas/middlesex/shepperton/house-clearance':          '/areas/surrey/shepperton/house-clearance',
    '/areas/middlesex/shepperton/office-clearance':         '/areas/surrey/shepperton/office-clearance',
    '/areas/middlesex/shepperton/residential-waste':        '/areas/surrey/shepperton/residential-waste',
    '/areas/middlesex/shepperton/rubble-wood-removal':      '/areas/surrey/shepperton/rubble-wood-removal',
    '/areas/middlesex/shepperton/scrap-metal-collection':   '/areas/surrey/shepperton/scrap-metal-collection',
    '/areas/middlesex/shepperton/skip-hire-alternative':    '/areas/surrey/shepperton/skip-hire-alternative',
    '/areas/middlesex/shepperton/strip-out-demolition':     '/areas/surrey/shepperton/strip-out-demolition',

    // ── Phase 1: Middlesex → Surrey (staines-upon-thames) ────────────────
    '/areas/middlesex/staines-upon-thames':                             '/areas/surrey/staines-upon-thames',
    '/areas/middlesex/staines-upon-thames/asbestos-removal':            '/areas/surrey/staines-upon-thames/asbestos-removal',
    '/areas/middlesex/staines-upon-thames/builders-waste-removal':      '/areas/surrey/staines-upon-thames/builders-waste-removal',
    '/areas/middlesex/staines-upon-thames/commercial-clearance':        '/areas/surrey/staines-upon-thames/commercial-clearance',
    '/areas/middlesex/staines-upon-thames/confidential-waste':          '/areas/surrey/staines-upon-thames/confidential-waste',
    '/areas/middlesex/staines-upon-thames/electrical-equipment':        '/areas/surrey/staines-upon-thames/electrical-equipment',
    '/areas/middlesex/staines-upon-thames/end-of-tenancy-clearance':    '/areas/surrey/staines-upon-thames/end-of-tenancy-clearance',
    '/areas/middlesex/staines-upon-thames/fly-tipping-removal':         '/areas/surrey/staines-upon-thames/fly-tipping-removal',
    '/areas/middlesex/staines-upon-thames/garden-refuse':               '/areas/surrey/staines-upon-thames/garden-refuse',
    '/areas/middlesex/staines-upon-thames/house-clearance':             '/areas/surrey/staines-upon-thames/house-clearance',
    '/areas/middlesex/staines-upon-thames/office-clearance':            '/areas/surrey/staines-upon-thames/office-clearance',
    '/areas/middlesex/staines-upon-thames/residential-waste':           '/areas/surrey/staines-upon-thames/residential-waste',
    '/areas/middlesex/staines-upon-thames/rubble-wood-removal':         '/areas/surrey/staines-upon-thames/rubble-wood-removal',
    '/areas/middlesex/staines-upon-thames/scrap-metal-collection':      '/areas/surrey/staines-upon-thames/scrap-metal-collection',
    '/areas/middlesex/staines-upon-thames/skip-hire-alternative':       '/areas/surrey/staines-upon-thames/skip-hire-alternative',
    '/areas/middlesex/staines-upon-thames/strip-out-demolition':        '/areas/surrey/staines-upon-thames/strip-out-demolition',

    // ── Phase 1: Middlesex → Surrey (stanwell) ───────────────────────────
    '/areas/middlesex/stanwell':                            '/areas/surrey/stanwell',
    '/areas/middlesex/stanwell/asbestos-removal':           '/areas/surrey/stanwell/asbestos-removal',
    '/areas/middlesex/stanwell/builders-waste-removal':     '/areas/surrey/stanwell/builders-waste-removal',
    '/areas/middlesex/stanwell/commercial-clearance':       '/areas/surrey/stanwell/commercial-clearance',
    '/areas/middlesex/stanwell/confidential-waste':         '/areas/surrey/stanwell/confidential-waste',
    '/areas/middlesex/stanwell/electrical-equipment':       '/areas/surrey/stanwell/electrical-equipment',
    '/areas/middlesex/stanwell/end-of-tenancy-clearance':   '/areas/surrey/stanwell/end-of-tenancy-clearance',
    '/areas/middlesex/stanwell/fly-tipping-removal':        '/areas/surrey/stanwell/fly-tipping-removal',
    '/areas/middlesex/stanwell/garden-refuse':              '/areas/surrey/stanwell/garden-refuse',
    '/areas/middlesex/stanwell/house-clearance':            '/areas/surrey/stanwell/house-clearance',
    '/areas/middlesex/stanwell/office-clearance':           '/areas/surrey/stanwell/office-clearance',
    '/areas/middlesex/stanwell/residential-waste':          '/areas/surrey/stanwell/residential-waste',
    '/areas/middlesex/stanwell/rubble-wood-removal':        '/areas/surrey/stanwell/rubble-wood-removal',
    '/areas/middlesex/stanwell/scrap-metal-collection':     '/areas/surrey/stanwell/scrap-metal-collection',
    '/areas/middlesex/stanwell/skip-hire-alternative':      '/areas/surrey/stanwell/skip-hire-alternative',
    '/areas/middlesex/stanwell/strip-out-demolition':       '/areas/surrey/stanwell/strip-out-demolition',

    // ── Phase 1: Middlesex → Surrey (sunbury-on-thames) ──────────────────
    '/areas/middlesex/sunbury-on-thames':                           '/areas/surrey/sunbury-on-thames',
    '/areas/middlesex/sunbury-on-thames/asbestos-removal':          '/areas/surrey/sunbury-on-thames/asbestos-removal',
    '/areas/middlesex/sunbury-on-thames/builders-waste-removal':    '/areas/surrey/sunbury-on-thames/builders-waste-removal',
    '/areas/middlesex/sunbury-on-thames/commercial-clearance':      '/areas/surrey/sunbury-on-thames/commercial-clearance',
    '/areas/middlesex/sunbury-on-thames/confidential-waste':        '/areas/surrey/sunbury-on-thames/confidential-waste',
    '/areas/middlesex/sunbury-on-thames/electrical-equipment':      '/areas/surrey/sunbury-on-thames/electrical-equipment',
    '/areas/middlesex/sunbury-on-thames/end-of-tenancy-clearance':  '/areas/surrey/sunbury-on-thames/end-of-tenancy-clearance',
    '/areas/middlesex/sunbury-on-thames/fly-tipping-removal':       '/areas/surrey/sunbury-on-thames/fly-tipping-removal',
    '/areas/middlesex/sunbury-on-thames/garden-refuse':             '/areas/surrey/sunbury-on-thames/garden-refuse',
    '/areas/middlesex/sunbury-on-thames/house-clearance':           '/areas/surrey/sunbury-on-thames/house-clearance',
    '/areas/middlesex/sunbury-on-thames/office-clearance':          '/areas/surrey/sunbury-on-thames/office-clearance',
    '/areas/middlesex/sunbury-on-thames/residential-waste':         '/areas/surrey/sunbury-on-thames/residential-waste',
    '/areas/middlesex/sunbury-on-thames/rubble-wood-removal':       '/areas/surrey/sunbury-on-thames/rubble-wood-removal',
    '/areas/middlesex/sunbury-on-thames/scrap-metal-collection':    '/areas/surrey/sunbury-on-thames/scrap-metal-collection',
    '/areas/middlesex/sunbury-on-thames/skip-hire-alternative':     '/areas/surrey/sunbury-on-thames/skip-hire-alternative',
    '/areas/middlesex/sunbury-on-thames/strip-out-demolition':      '/areas/surrey/sunbury-on-thames/strip-out-demolition',

    // ── Phase 3: West London → Central London (fitzrovia) ────────────────
    '/areas/west-london/fitzrovia':                             '/areas/central-london/fitzrovia',
    '/areas/west-london/fitzrovia/asbestos-removal':            '/areas/central-london/fitzrovia/asbestos-removal',
    '/areas/west-london/fitzrovia/builders-waste-removal':      '/areas/central-london/fitzrovia/builders-waste-removal',
    '/areas/west-london/fitzrovia/commercial-clearance':        '/areas/central-london/fitzrovia/commercial-clearance',
    '/areas/west-london/fitzrovia/confidential-waste':          '/areas/central-london/fitzrovia/confidential-waste',
    '/areas/west-london/fitzrovia/electrical-equipment':        '/areas/central-london/fitzrovia/electrical-equipment',
    '/areas/west-london/fitzrovia/end-of-tenancy-clearance':    '/areas/central-london/fitzrovia/end-of-tenancy-clearance',
    '/areas/west-london/fitzrovia/fly-tipping-removal':         '/areas/central-london/fitzrovia/fly-tipping-removal',
    '/areas/west-london/fitzrovia/garden-refuse':               '/areas/central-london/fitzrovia/garden-refuse',
    '/areas/west-london/fitzrovia/house-clearance':             '/areas/central-london/fitzrovia/house-clearance',
    '/areas/west-london/fitzrovia/office-clearance':            '/areas/central-london/fitzrovia/office-clearance',
    '/areas/west-london/fitzrovia/residential-waste':           '/areas/central-london/fitzrovia/residential-waste',
    '/areas/west-london/fitzrovia/rubble-wood-removal':         '/areas/central-london/fitzrovia/rubble-wood-removal',
    '/areas/west-london/fitzrovia/scrap-metal-collection':      '/areas/central-london/fitzrovia/scrap-metal-collection',
    '/areas/west-london/fitzrovia/skip-hire-alternative':       '/areas/central-london/fitzrovia/skip-hire-alternative',
    '/areas/west-london/fitzrovia/strip-out-demolition':        '/areas/central-london/fitzrovia/strip-out-demolition',

    // ── Phase 3: Middlesex → North London (enfield duplicate) ────────────
    '/areas/middlesex/enfield':                             '/areas/north-london/enfield',
    '/areas/middlesex/enfield/asbestos-removal':            '/areas/north-london/enfield/asbestos-removal',
    '/areas/middlesex/enfield/builders-waste-removal':      '/areas/north-london/enfield/builders-waste-removal',
    '/areas/middlesex/enfield/commercial-clearance':        '/areas/north-london/enfield/commercial-clearance',
    '/areas/middlesex/enfield/confidential-waste':          '/areas/north-london/enfield/confidential-waste',
    '/areas/middlesex/enfield/electrical-equipment':        '/areas/north-london/enfield/electrical-equipment',
    '/areas/middlesex/enfield/end-of-tenancy-clearance':    '/areas/north-london/enfield/end-of-tenancy-clearance',
    '/areas/middlesex/enfield/fly-tipping-removal':         '/areas/north-london/enfield/fly-tipping-removal',
    '/areas/middlesex/enfield/garden-refuse':               '/areas/north-london/enfield/garden-refuse',
    '/areas/middlesex/enfield/house-clearance':             '/areas/north-london/enfield/house-clearance',
    '/areas/middlesex/enfield/office-clearance':            '/areas/north-london/enfield/office-clearance',
    '/areas/middlesex/enfield/residential-waste':           '/areas/north-london/enfield/residential-waste',
    '/areas/middlesex/enfield/rubble-wood-removal':         '/areas/north-london/enfield/rubble-wood-removal',
    '/areas/middlesex/enfield/scrap-metal-collection':      '/areas/north-london/enfield/scrap-metal-collection',
    '/areas/middlesex/enfield/skip-hire-alternative':       '/areas/north-london/enfield/skip-hire-alternative',
    '/areas/middlesex/enfield/strip-out-demolition':        '/areas/north-london/enfield/strip-out-demolition',
  },
  integrations: [
    mdx(),
    sitemap({
      serialize(item) {
        // Strip trailing slash from all URLs except the homepage to match canonical format
        if (item.url !== 'https://wastewize.co.uk/') {
          item.url = item.url.replace(/\/$/, '');
        }
        return item;
      },
    }),
  ],

  build: {
    inlineStylesheets: 'always',
  },
  vite: {
    plugins: [tailwindcss()],
  },
});